### PR TITLE
Fixed bug with FPC 3.0.0 compilation error

### PR DESCRIPTION
**Pull request by tnt4brain**
These changes make compilation possible back again (please see https://github.com/RRUZ/wmi-delphi-code-creator/issues/29)

### CODE REVIEW

**Review by mtournay — APPROVED** [review]
This patch also work with fpc3.0.4

**Comment by tnt4brain** [comment]
Could you please merge?
